    <?php if ($cotizacionEdicionId > 0): ?><div class="aviso revision-banner-ui revision-cotizacion-ui" style="margin-bottom:12px;background:#fff3cd;border:1px solid #ffecb5;color:#664d03;padding:12px;border-radius:8px;"><strong>Está modificando la revisión <?= (int)$cotizacionEdicion['revision'] ?>.</strong> Al guardar se conservará el mismo número y se generará la revisión <?= (int)$cotizacionEdicion['revision'] + 1 ?>.<label for="motivo_modificacion_cotizacion" style="display:block;margin-top:9px;font-weight:700;">Detalle de la modificación *</label><textarea id="motivo_modificacion_cotizacion" name="motivo_modificacion_cotizacion" form="form_cotizador" maxlength="500" required placeholder="Ej.: Se agregó luz de emergencia y se corrigió la cantidad de límites." style="width:100%;min-height:58px;margin-top:5px;padding:8px;border:1px solid #d7b95c;border-radius:6px;resize:vertical;font:inherit;"></textarea><div style="font-size:12px;margin-top:5px;">Este texto quedará registrado en el historial y aparecerá junto al número de revisión en el PDF.</div></div><?php endif; ?>
    <?php if ($pedidoEdicionId > 0): ?><div class="aviso revision-banner-ui revision-pedido-ui" style="margin-bottom:12px;background:#f8d7da;border:1px solid #f1aeb5;color:#842029;padding:10px;border-radius:6px;"><strong>Modificación de pedido <?= escapar($pedidoEdicion['pedido_numero']) ?></strong><div class="revision-pedido-info">Revisión vigente: <?= (int)$pedidoEdicion['revision'] ?>. El número de pedido y de obra se conservarán. Al guardar se generará la revisión <?= (int)$pedidoEdicion['revision'] + 1 ?> para Producción y Administración.</div><label for="motivo_modificacion_pedido">Detalle de la modificación *</label><textarea name="motivo_modificacion_pedido" id="motivo_modificacion_pedido" form="form_cotizador" rows="3" maxlength="2000" required data-excluir-calculo-auxiliar="1" placeholder="Ej.: Se modificó la cantidad de paradas y se agregó luz de emergencia."></textarea><div class="revision-pedido-ayuda">Este texto quedará registrado en el historial del pedido y acompañará a la nueva revisión para Producción y Administración.</div></div><?php endif; ?>
    <?php if ($pedidoEdicionId > 0 && $pedidoConfiguracionNoDisponible): ?><div class="aviso" style="margin-bottom:12px;background:#fff3cd;border:1px solid #ffecb5;color:#664d03;padding:12px;border-radius:6px;line-height:1.45;"><strong>Pedido histórico sin configuración técnica guardada.</strong><br>Este pedido fue creado con una versión anterior que guardó <code>datos_formulario = 0</code>. Se recuperaron cliente, lista, referencia y descuentos, pero los selectores técnicos deben reconstruirse una sola vez usando el detalle o PDF original. Al guardar la nueva revisión, la configuración completa quedará almacenada y las próximas modificaciones cargarán todos los datos automáticamente.</div><?php endif; ?>

    <?php if ($modoPlantilla !== 'nueva' && $modoPlantilla !== 'editar'): ?>

    <div class="cotizador-flujo-wrap">
      <div class="cotizador-flujo-cabecera"><div><strong><span class="paso-numero">2</span> Flujo de cotización</strong><br><small>Avance en orden. En cada etapa puede incluir el módulo o indicar que no lo lleva.</small></div></div>
      <div class="cotizador-modulos flujo-principal" role="tablist" aria-label="Flujo de cotización">
        <button type="button" class="cotizador-modulo-btn activo" data-modulo="control" role="tab" aria-selected="true" onclick="seleccionarModuloFlujo('control')"><span class="paso-chip">1</span> Control</button>
        <button type="button" class="cotizador-modulo-btn" data-modulo="senalizacion" role="tab" aria-selected="false" onclick="seleccionarModuloFlujo('senalizacion')"><span class="paso-chip">2</span> Señalización</button>
        <button type="button" class="cotizador-modulo-btn" data-modulo="accesorios" role="tab" aria-selected="false" onclick="seleccionarModuloFlujo('accesorios')"><span class="paso-chip">3</span> Accesorios</button>
        <button type="button" class="cotizador-modulo-btn" data-modulo="iep" role="tab" aria-selected="false" onclick="seleccionarModuloFlujo('iep')"><span class="paso-chip">4</span> IEP</button>
      </div>
      <div class="cotizador-repuestos-independiente"><span><strong>Repuestos integrados:</strong> pueden agregarse junto con Control, Señalización, Accesorios o IEP, o cotizarse solos.</span><button type="button" class="cotizador-modulo-btn" data-modulo="repuestos" role="tab" aria-selected="false" onclick="seleccionarModuloFlujo('repuestos')">◆ Ir a Repuestos</button></div>
    </div>
    <?php endif; ?>

