<?php
session_start();require_once 'conexion.php';require_once 'auth.php';exigirRoles(array('ADMINISTRADOR'));
$mensaje='';$error='';
function numeroArRep($v){$v=trim(str_replace(array('$',' '),'',(string)$v));if($v==='')return null;if(strpos($v,',')!==false)$v=str_replace(',','.',str_replace('.','',$v));elseif(substr_count($v,'.')===1&&strlen(substr(strrchr($v,'.'),1))===3)$v=str_replace('.','',$v);return is_numeric($v)?(float)$v:null;}
function abrirCsvRep($tmp){$h=fopen($tmp,'rb');if(!$h)throw new Exception('No se pudo abrir el CSV.');$bom=fread($h,3);if($bom!=="\xEF\xBB\xBF")rewind($h);return $h;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  if(empty($_FILES['bejerman_csv']['tmp_name']))throw new Exception('Seleccione Bejerman.csv.');
  $conexion->begin_transaction();$h=abrirCsvRep($_FILES['bejerman_csv']['tmp_name']);$filas=array();$rubro='';$sub='';$fecha='';$mo=0;$usd=0;
  while(($r=fgetcsv($h,0,','))!==false){if(!$r)continue;$a=trim((string)($r[0]??''));for($i=0;$i<count($r);$i++){$k=mb_strtolower(trim((string)$r[$i]),'UTF-8');$v=trim((string)($r[$i+1]??''));if($k==='fecha lista')$fecha=$v;elseif($k==='mano de obra')$mo=numeroArRep($v)??0;elseif($k==='valor dolar')$usd=numeroArRep($v)??0;}if(strpos($a,'Rubro:')===0){$rubro=trim(substr($a,6));continue;}if(strpos($a,'Subrubro:')===0){$sub=trim(substr($a,9));continue;}$c=numeroArRep($r[3]??'');if($a!==''&&$c!==null)$filas[]=array($a,trim((string)($r[1]??'')),trim((string)($r[2]??'')),$rubro,$sub,$c,numeroArRep($r[8]??''));}fclose($h);
  $dt=DateTime::createFromFormat('d/m/Y',$fecha);if(!$dt)throw new Exception('No se encontró una Fecha Lista válida.');
  $conexion->query("UPDATE bejerman_listas SET estado='HISTORICA' WHERE estado='VIGENTE'");$usuario=$_SESSION['usuario_nombre']??'';$archivo=$_FILES['bejerman_csv']['name'];$st=$conexion->prepare("INSERT INTO bejerman_listas(fecha_lista,valor_mano_obra,valor_dolar,usuario_importacion,archivo_origen,estado) VALUES(?,?,?,?,?,'VIGENTE')");$fechaSql=$dt->format('Y-m-d');$st->bind_param('sddss',$fechaSql,$mo,$usd,$usuario,$archivo);$st->execute();$listaId=$st->insert_id;$st->close();
  $st=$conexion->prepare('INSERT INTO bejerman_productos(bejerman_lista_id,codigo,descripcion,unidad,rubro,subrubro,costo,valor_dolar_articulo,activo) VALUES(?,?,?,?,?,?,?,?,1)');foreach($filas as $x){$st->bind_param('isssssdd',$listaId,$x[0],$x[1],$x[2],$x[3],$x[4],$x[5],$x[6]);$st->execute();}$st->close();
  if(!empty($_FILES['productos_csv']['tmp_name'])){$h=abrirCsvRep($_FILES['productos_csv']['tmp_name']);$cab=fgetcsv($h,0,',');$st=$conexion->prepare("INSERT INTO productos_repuestos(codigo,descripcion,categoria,costo_referencia,utilidad,factor_descuento_15,factor_descuento_30,observaciones,es_neto,iva_porcentaje,advertencia,habilitado) VALUES(?,?,?,?,?,?,?,?,?,?,?,1) ON DUPLICATE KEY UPDATE descripcion=VALUES(descripcion),categoria=VALUES(categoria),costo_referencia=VALUES(costo_referencia),utilidad=VALUES(utilidad),factor_descuento_15=VALUES(factor_descuento_15),factor_descuento_30=VALUES(factor_descuento_30),observaciones=VALUES(observaciones),es_neto=VALUES(es_neto),iva_porcentaje=VALUES(iva_porcentaje),advertencia=VALUES(advertencia),habilitado=1");$n=0;while(($r=fgetcsv($h,0,','))!==false){$cod=trim((string)($r[0]??''));if($cod==='')continue;$costo=numeroArRep($r[3]??'')??0;$ut=numeroArRep($r[4]??'')??1;$p=numeroArRep($r[5]??'')?:($costo*$ut);$p15=numeroArRep($r[6]??'')??($p*.85);$p30=numeroArRep($r[7]??'')??($p*.70);$f15=$p>0?$p15/$p:.85;$f30=$p>0?$p30/$p:.70;$neto=in_array(mb_strtoupper(trim((string)($r[9]??'')),'UTF-8'),array('VERDADERO','TRUE','SI','1'),true)?1:0;$iva=numeroArRep($r[10]??'')??0;$st->bind_param('sssddddsids',$cod,$r[1],$r[2],$costo,$ut,$f15,$f30,$r[8],$neto,$iva,$r[11]);$st->execute();$n++;}$st->close();fclose($h);}
  $conexion->commit();$mensaje='Base Bejerman actualizada: '.count($filas).' artículos.';
 }catch(Throwable $e){$conexion->rollback();$error=$e->getMessage();}
}
$lista=$conexion->query("SELECT * FROM bejerman_listas WHERE estado='VIGENTE' ORDER BY bejerman_lista_id DESC LIMIT 1")->fetch_assoc();$cant=(int)($conexion->query("SELECT COUNT(*) c FROM productos_repuestos WHERE habilitado=1")->fetch_assoc()['c']??0);
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Administrar repuestos</title><style>body{font-family:Arial;margin:18px;background:#f4f4f9}.caja{max-width:900px;background:#fff;padding:20px;border-radius:8px;box-shadow:0 0 10px #0002}.fila{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{display:block;font-weight:bold;margin:10px 0 4px}input{width:100%;padding:9px}button{margin-top:16px;padding:10px 18px;background:#198754;color:#fff;border:0;border-radius:5px;font-weight:bold}.ok{background:#d1e7dd;padding:10px}.err{background:#f8d7da;padding:10px}@media(max-width:700px){.fila{grid-template-columns:1fr}}</style></head><body><?php require 'menu.php';?><div class="caja"><h1>Base Bejerman y Repuestos</h1><?php if($mensaje):?><div class="ok"><?=htmlspecialchars($mensaje)?></div><?php endif;?><?php if($error):?><div class="err"><?=htmlspecialchars($error)?></div><?php endif;?><p><strong>Lista vigente:</strong> <?=htmlspecialchars($lista['fecha_lista']??'Sin importar')?> &nbsp; <strong>Mano de obra:</strong> $ <?=number_format((float)($lista['valor_mano_obra']??0),2,',','.')?> &nbsp; <strong>Dólar:</strong> $ <?=number_format((float)($lista['valor_dolar']??0),2,',','.')?></p><p><strong>Repuestos habilitados:</strong> <?=$cant?></p><form method="post" enctype="multipart/form-data"><div class="fila"><div><label>Bejerman.csv *</label><input type="file" name="bejerman_csv" accept=".csv" required></div><div><label>Productos.csv (opcional)</label><input type="file" name="productos_csv" accept=".csv"><small>Úselo cuando cambien categorías, utilidades, descuentos, IVA o advertencias.</small></div></div><button>IMPORTAR ACTUALIZACIÓN</button></form></div></body></html>