<?php
session_start();
require_once 'conexion.php';
require_once 'auth.php';
asegurarSistemaUsuarios($conexion);
exigirRoles(array('ADMINISTRADOR','COMERCIAL','TECNICO'));
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Calculadora · AUTOMAC</title><link rel="stylesheet" href="automac-ui.css"><style>
.calc-wrap{max-width:430px;margin:28px auto;padding:0 16px 50px}.calc-card{background:#fff;border:1px solid #dce4ec;border-radius:16px;padding:16px;box-shadow:0 12px 30px rgba(15,23,42,.08)}.calc-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.calc-head h1{font-size:19px;margin:0;color:#17324d}.calc-head small{color:#64748b}.calc-display{width:100%;height:72px;border:1px solid #cbd5e1;border-radius:12px;background:#f8fafc;padding:10px 14px;text-align:right;font-size:30px;font-weight:800;color:#0f172a;box-sizing:border-box;margin-bottom:12px}.calc-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.calc-btn{height:55px;border:1px solid #d7e0ea;border-radius:10px;background:#fff;color:#1e293b;font-size:18px;font-weight:800;cursor:pointer}.calc-btn:hover{background:#f1f5f9}.calc-btn.op{background:#eef5ff;color:#0b5ed7}.calc-btn.eq{background:#0d6efd;color:#fff;border-color:#0d6efd}.calc-btn.clear{background:#fff0f0;color:#b42318}.calc-note{margin-top:12px;font-size:12px;color:#64748b;line-height:1.45}</style></head><body><?php require 'menu.php';?><main class="calc-wrap"><section class="calc-card"><div class="calc-head"><div><h1>Calculadora</h1><small>Herramienta rápida del cotizador</small></div></div><input id="display" class="calc-display" value="0" readonly aria-label="Resultado"><div class="calc-grid">
<button class="calc-btn clear" data-a="clear">C</button><button class="calc-btn" data-a="back">⌫</button><button class="calc-btn op" data-v="%">%</button><button class="calc-btn op" data-v="/">÷</button>
<button class="calc-btn" data-v="7">7</button><button class="calc-btn" data-v="8">8</button><button class="calc-btn" data-v="9">9</button><button class="calc-btn op" data-v="*">×</button>
<button class="calc-btn" data-v="4">4</button><button class="calc-btn" data-v="5">5</button><button class="calc-btn" data-v="6">6</button><button class="calc-btn op" data-v="-">−</button>
<button class="calc-btn" data-v="1">1</button><button class="calc-btn" data-v="2">2</button><button class="calc-btn" data-v="3">3</button><button class="calc-btn op" data-v="+">+</button>
<button class="calc-btn" data-v="0" style="grid-column:span 2">0</button><button class="calc-btn" data-v=".">,</button><button class="calc-btn eq" data-a="eq">=</button>
</div><div class="calc-note">También podés usar el teclado numérico, +, −, ×, ÷, Enter y Escape.</div></section></main><script>
(()=>{const d=document.getElementById('display');let expr='';const show=()=>{d.value=expr||'0'};const add=v=>{if(expr.length<80){expr+=v;show()}};const calc=()=>{try{if(!expr)return;const safe=expr.replace(/%/g,'/100');if(!/^[0-9+\-*/.()\s]+$/.test(safe))throw 0;const r=Function('"use strict";return ('+safe+')')();if(!Number.isFinite(r))throw 0;expr=String(Math.round((r+Number.EPSILON)*100000000)/100000000);show()}catch(e){d.value='Error';expr=''}};document.querySelectorAll('.calc-btn').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.v)add(b.dataset.v);else if(b.dataset.a==='clear'){expr='';show()}else if(b.dataset.a==='back'){expr=expr.slice(0,-1);show()}else if(b.dataset.a==='eq')calc()}));window.addEventListener('keydown',e=>{if(/[0-9.+\-*/%()]/.test(e.key)&&e.key.length===1){add(e.key);e.preventDefault()}else if(e.key==='Enter'||e.key==='='){calc();e.preventDefault()}else if(e.key==='Backspace'){expr=expr.slice(0,-1);show();e.preventDefault()}else if(e.key==='Escape'){expr='';show();e.preventDefault()}});})();
</script></body></html>
