<?php
require_once 'auth.php';
require_once 'conexion.php';
require_once 'control_parametros.php';
exigirRoles(array('ADMINISTRADOR'));
function mctlE($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function mctlCount(mysqli $c,string $t):int{$r=$c->query("SELECT COUNT(*) c FROM `$t`");return $r?(int)$r->fetch_assoc()['c']:0;}
$counts=array();foreach(array('matriz_calculos','cpus','tipos_control','subtipos_control','centrales','contactores','contactorpot','termicos','baterias','matriz_baterias','posicionamiento_encoder_permitido','rescates_opciones','rescates_componentes','ptacabina','ptapisos') as $t){$counts[$t]=mctlCount($conexion,$t);}
$tab=$_GET['tab']??'principal';
$tabs=array('principal'=>'Matriz principal','catalogos'=>'CPUs y tipos','potencias'=>'Potencias / contactores','termicos'=>'Térmicos','baterias'=>'Baterías y rescates','encoder'=>'Encoder','puertas'=>'Puertas','comunicacion'=>'Comunicación','adicionales'=>'Adicionales','dependencias'=>'Dependencias');if(!isset($tabs[$tab]))$tab='principal';

// v212: vista operativa integrada de la matriz principal. La edición profunda sigue usando
// administrar_matriz.php para reutilizar las validaciones históricas ya probadas.
$fCpu=(int)($_GET['cpu']??0);
$fTipo=(int)($_GET['tipo']??0);
$fSubtipo=(int)($_GET['subtipo']??0);
$fBuscar=trim((string)($_GET['q']??''));
$cpusLista=$conexion->query('SELECT cpu_id,cpu_name FROM cpus ORDER BY cpu_name');
$tiposLista=$conexion->query('SELECT ctrltipo_id,ctrltipo_name FROM tipos_control ORDER BY ctrltipo_id');
$subtiposLista=$conexion->query('SELECT ctrlsubtipo_id,ctrlsubtipo_name FROM subtipos_control ORDER BY ctrlsubtipo_name');
$modelosControl=$conexion->query("SELECT c.cpu_id,c.cpu_name,COALESCE(cap.activo,'SI') activo,c.velocidad_max_mmin,c.admite_encoder,b.cpu_name base_nombre,(SELECT COUNT(*) FROM matriz_calculos m WHERE m.control_cpu=c.cpu_id) filas_propias,(SELECT COUNT(*) FROM control_compatibilidades cc WHERE cc.cpu_id=c.cpu_id AND cc.activo='SI') compat_activas FROM cpus c LEFT JOIN control_cpu_capacidades cap ON cap.cpu_id=c.cpu_id LEFT JOIN cpus b ON b.cpu_id=COALESCE(NULLIF(c.cpu_matriz_base_id,0),c.cpu_id) ORDER BY c.cpu_name");
$matrizListado=null; $matrizTotal=0;
if($tab==='principal'){
  $sql="SELECT m.control_id,m.control_codigo,m.control_potenciadesde,m.control_potenciahasta,m.control_corriente,m.control_encoder,m.control_precio,
               c.cpu_name,tc.ctrltipo_name,sc.ctrlsubtipo_name,t.tension_name,co.contactor_name,cp.contactorpot_name,th.termicos_codigo,
               lp.precios_descripcion,lp.precios_costo
        FROM matriz_calculos m
        INNER JOIN cpus c ON c.cpu_id=m.control_cpu
        INNER JOIN tipos_control tc ON tc.ctrltipo_id=m.control_tipo
        INNER JOIN subtipos_control sc ON sc.ctrlsubtipo_id=m.control_subtipo
        INNER JOIN tensiones t ON t.tension_id=m.control_tension
        LEFT JOIN contactores co ON co.contactor_id=m.control_contactor
        LEFT JOIN contactorpot cp ON cp.contactorpot_id=m.control_contactorpot
        LEFT JOIN termicos th ON th.termicos_id=m.control_termicos
        LEFT JOIN lista_precios lp ON TRIM(lp.precios_codigo)=TRIM(m.control_codigo)
        WHERE 1=1";
  $types=''; $vals=array();
  if($fCpu){$sql.=' AND m.control_cpu=?';$types.='i';$vals[]=$fCpu;}
  if($fTipo){$sql.=' AND m.control_tipo=?';$types.='i';$vals[]=$fTipo;}
  if($fSubtipo){$sql.=' AND m.control_subtipo=?';$types.='i';$vals[]=$fSubtipo;}
  if($fBuscar!==''){$sql.=' AND (m.control_codigo LIKE ? OR lp.precios_descripcion LIKE ? OR c.cpu_name LIKE ? OR sc.ctrlsubtipo_name LIKE ?)';$types.='ssss';$b='%'.$fBuscar.'%';array_push($vals,$b,$b,$b,$b);}
  $sql.=' ORDER BY c.cpu_name,tc.ctrltipo_id,sc.ctrlsubtipo_name,t.tension_name,m.control_potenciadesde LIMIT 500';
  $st=$conexion->prepare($sql);
  if($types!==''){ $refs=array($types); foreach($vals as $k=>$v){$refs[]=&$vals[$k];} call_user_func_array(array($st,'bind_param'),$refs); }
  $st->execute(); $matrizListado=$st->get_result(); $matrizTotal=$matrizListado->num_rows;
}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><title>Matrices de Control · Automac</title><link rel="stylesheet" href="automac-ui.css"><style>
.main{padding:24px;max-width:1500px;margin:auto}.hero,.card{background:#fff;border:1px solid #dfe5ec;border-radius:12px;padding:16px;margin-bottom:14px}.hero h1{margin:0 0 6px}.hero p{margin:0;color:#64748b}.tabs{display:flex;gap:7px;flex-wrap:wrap;margin:0 0 14px}.tabs a{padding:8px 10px;border:1px solid #ced8e2;border-radius:8px;text-decoration:none;color:#234;background:#fff}.tabs a.on{background:#0f5f9c;color:white;border-color:#0f5f9c}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.mini{font-size:12px;color:#64748b}.kpi strong{font-size:28px;display:block}.btn{display:inline-block;text-decoration:none;border-radius:8px;padding:9px 12px;background:#0f5f9c;color:#fff;font-weight:700;margin:4px 4px 0 0}.btn.sec{background:#edf3f7;color:#234}.warn{padding:12px;border-radius:9px;background:#fff7df;border:1px solid #eed69a;color:#665116}.tech{font-family:ui-monospace,Consolas,monospace;font-size:12px;color:#52606d}.filters{display:grid;grid-template-columns:repeat(4,minmax(160px,1fr)) auto;gap:8px;align-items:end;margin:12px 0}.filters label{font-size:12px;font-weight:700;color:#52606d}.filters select,.filters input{width:100%;box-sizing:border-box;padding:8px;border:1px solid #ccd6df;border-radius:7px;background:#fff}.tablewrap{overflow:auto;max-height:650px;border:1px solid #dfe5ec;border-radius:9px}table.matrix{width:100%;border-collapse:collapse;font-size:12px;white-space:nowrap}table.matrix th,table.matrix td{padding:7px 8px;border-bottom:1px solid #e7edf2;text-align:left}table.matrix th{position:sticky;top:0;background:#243746;color:#fff;z-index:2}table.matrix tr:hover{background:#f4f9fd}.bad{color:#b42318;font-weight:700}.good{color:#18794e;font-weight:700}.actions{display:flex;gap:5px}.btn.sm{padding:6px 8px;font-size:11px}.note{font-size:12px;color:#667085;margin-top:8px}@media(max-width:900px){.filters{grid-template-columns:1fr 1fr}}
</style></head><body><?php require 'menu.php';?><main class="main"><section class="hero"><h1>Matrices de Control</h1><p>Vista unificada de la configuración de Control. Los editores existentes se conservan mientras se migra cada catálogo a esta pantalla para no romper el motor vigente.</p></section><nav class="tabs"><?php foreach($tabs as $k=>$v):?><a class="<?=$tab===$k?'on':''?>" href="?tab=<?=mctlE($k)?>"><?=mctlE($v)?></a><?php endforeach;?></nav>
<?php if($tab==='principal'):?><section class="card"><div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap"><div><h2 style="margin:0 0 5px">Matriz principal</h2><p style="margin:0">CPU + tipo + subtipo + tensión + rango de potencia + contactores/térmico + código Bejerman.</p></div><div><a class="btn" href="administrar_matriz.php#formulario-configuracion">+ Nueva combinación</a><a class="btn sec" href="exportar_matriz_calculos.php">Exportar</a></div></div>
<form class="filters" method="get"><input type="hidden" name="tab" value="principal"><label>CPU<select name="cpu"><option value="0">Todas</option><?php if($cpusLista) while($x=$cpusLista->fetch_assoc()):?><option value="<?=(int)$x['cpu_id']?>"<?=$fCpu===(int)$x['cpu_id']?' selected':''?>><?=mctlE($x['cpu_name'])?></option><?php endwhile;?></select></label><label>Tipo<select name="tipo"><option value="0">Todos</option><?php if($tiposLista) while($x=$tiposLista->fetch_assoc()):?><option value="<?=(int)$x['ctrltipo_id']?>"<?=$fTipo===(int)$x['ctrltipo_id']?' selected':''?>><?=mctlE($x['ctrltipo_name'])?></option><?php endwhile;?></select></label><label>Subtipo<select name="subtipo"><option value="0">Todos</option><?php if($subtiposLista) while($x=$subtiposLista->fetch_assoc()):?><option value="<?=(int)$x['ctrlsubtipo_id']?>"<?=$fSubtipo===(int)$x['ctrlsubtipo_id']?' selected':''?>><?=mctlE($x['ctrlsubtipo_name'])?></option><?php endwhile;?></select></label><label>Buscar<input name="q" value="<?=mctlE($fBuscar)?>" placeholder="Código, descripción, CPU..."></label><div><button class="btn" type="submit">Filtrar</button><a class="btn sec" href="?tab=principal">Limpiar</a></div></form>
<div class="mini" style="margin-bottom:8px"><strong><?=$matrizTotal?></strong> filas mostradas · <?=$counts['matriz_calculos']?> combinaciones totales.</div><div class="tablewrap"><table class="matrix"><thead><tr><th>CPU</th><th>Tipo</th><th>Subtipo</th><th>Tensión</th><th>HP desde</th><th>HP hasta</th><th>Contactor</th><th>Cont. pot.</th><th>Térmico</th><th>Código</th><th>Base Bejerman</th><th>Acciones</th></tr></thead><tbody><?php if($matrizListado && $matrizListado->num_rows): while($r=$matrizListado->fetch_assoc()):?><tr><td><strong><?=mctlE($r['cpu_name'])?></strong></td><td><?=mctlE($r['ctrltipo_name'])?></td><td><?=mctlE($r['ctrlsubtipo_name'])?></td><td><?=mctlE($r['tension_name'])?></td><td><?=mctlE($r['control_potenciadesde'])?></td><td><?=mctlE($r['control_potenciahasta'])?></td><td><?=mctlE($r['contactor_name']?:'—')?></td><td><?=mctlE($r['contactorpot_name']?:'—')?></td><td><?=mctlE($r['termicos_codigo']?:'—')?></td><td><span class="tech"><?=mctlE($r['control_codigo'])?></span></td><td class="<?=($r['precios_costo']===null||(float)$r['precios_costo']<=0)?'bad':'good'?>"><?=($r['precios_costo']===null?'NO EXISTE':((float)$r['precios_costo']<=0?'PRECIO 0':'OK'))?></td><td><div class="actions"><a class="btn sm" href="administrar_matriz.php?editar=<?=(int)$r['control_id']?>#formulario-configuracion">Editar</a><a class="btn sec sm" href="administrar_matriz.php?duplicar=<?=(int)$r['control_id']?>#formulario-configuracion">Duplicar</a></div></td></tr><?php endwhile; else:?><tr><td colspan="12">No hay combinaciones para esos filtros.</td></tr><?php endif;?></tbody></table></div><p class="note">La edición abre el formulario técnico existente para conservar todas sus validaciones y controles de duplicados. La búsqueda y navegación ya quedan centralizadas en Matrices de Control.</p></section>
<?php elseif($tab==='catalogos'):?><section class="card"><h2>CPUs, tipos y subtipos</h2><p><a class="btn" href="mantenimiento_control_nuevo_modelo.php">+ Nuevo modelo de Control</a><a class="btn sec" href="mantenimiento_control_compatibilidades.php">Compatibilidades globales</a></p><div class="grid"><div class="kpi"><strong><?=$counts['cpus']?></strong><span>CPUs</span></div><div class="kpi"><strong><?=$counts['tipos_control']?></strong><span>tipos</span></div><div class="kpi"><strong><?=$counts['subtipos_control']?></strong><span>subtipos</span></div></div><p class="warn"><strong>v216:</strong> cada modelo existente ya puede editarse desde una vista unificada: identidad, estado, capacidades, matriz base y Tipo + Subtipo. Las filas económicas se siguen editando con el editor de matriz probado.</p><div class="tablewrap" style="margin-top:12px"><table class="matrix"><thead><tr><th>Modelo</th><th>Estado</th><th>Matriz base</th><th>Vel. máx.</th><th>Encoder</th><th>Compat.</th><th>Filas propias</th><th>Acciones</th></tr></thead><tbody><?php if($modelosControl) while($m=$modelosControl->fetch_assoc()):?><tr><td><strong><?=mctlE($m['cpu_name'])?></strong></td><td><?=mctlE($m['activo'])?></td><td><?=mctlE($m['base_nombre']?:$m['cpu_name'])?></td><td><?=mctlE($m['velocidad_max_mmin']??'—')?></td><td><?=mctlE($m['admite_encoder']??'—')?></td><td><?=(int)$m['compat_activas']?></td><td><?=(int)$m['filas_propias']?></td><td><a class="btn sm" href="mantenimiento_control_editar_modelo.php?cpu=<?=(int)$m['cpu_id']?>">Editar modelo</a><a class="btn sec sm" href="?tab=principal&cpu=<?=(int)$m['cpu_id']?>">Matriz</a></td></tr><?php endwhile;?></tbody></table></div><p><a class="btn sec" href="administrar_matriz.php#tipos">Tipos</a><a class="btn sec" href="administrar_matriz.php#subtipos">Subtipos</a></p></section>
<?php elseif($tab==='potencias'):?><section class="card"><h2>Potencias y contactores</h2><div class="grid"><div class="kpi"><strong><?=$counts['contactores']?></strong><span>contactores principales</span></div><div class="kpi"><strong><?=$counts['contactorpot']?></strong><span>contactores de potencial</span></div></div><p>Las relaciones operativas se encuentran principalmente en <span class="tech">matriz_calculos</span>.</p><a class="btn" href="administrar_matriz.php">Editar combinaciones</a></section>
<?php elseif($tab==='termicos'):?><section class="card"><h2>Térmicos</h2><div class="kpi"><strong><?=$counts['termicos']?></strong><span>registros</span></div><p>Se conservarán como catálogo técnico relacionado con las combinaciones de Control.</p><a class="btn" href="administrar_matriz.php">Ver uso en matriz</a></section>
<?php elseif($tab==='baterias'):?><section class="card"><h2>Baterías y rescates</h2><div class="grid"><div class="kpi"><strong><?=$counts['baterias']?></strong><span>agrupaciones</span></div><div class="kpi"><strong><?=$counts['matriz_baterias']?></strong><span>reglas de baterías</span></div><div class="kpi"><strong><?=$counts['rescates_opciones']?></strong><span>rescates</span></div><div class="kpi"><strong><?=$counts['rescates_componentes']?></strong><span>componentes</span></div></div><a class="btn" href="mantenimiento_catalogos_control.php">Editar catálogos actuales</a><a class="btn sec" href="mantenimiento_rescates.php">Administrar rescates</a></section>
<?php elseif($tab==='encoder'):?><section class="card"><h2>Encoder</h2><div class="kpi"><strong><?=$counts['posicionamiento_encoder_permitido']?></strong><span>compatibilidades</span></div><p>CPU/tipo/subtipo/velocidad permitidos.</p><a class="btn" href="administrar_matriz.php">Revisar matriz</a></section>
<?php elseif($tab==='puertas'):?><section class="card"><h2>Puertas</h2><div class="grid"><div class="kpi"><strong><?=$counts['ptacabina']?></strong><span>puertas de cabina</span></div><div class="kpi"><strong><?=$counts['ptapisos']?></strong><span>puertas de piso</span></div></div><a class="btn" href="administrar_matriz.php">Ver combinaciones</a></section>
<?php elseif($tab==='comunicacion'):?><section class="card"><h2>Comunicación</h2><p>Paralelo/serie y compatibilidades se cruzan con la matriz principal y límites de paradas.</p><a class="btn" href="administrar_matriz.php">Matriz principal</a><a class="btn sec" href="limites_paradas.php">Límites de paradas</a></section>
<?php elseif($tab==='adicionales'):?><section class="card"><h2>Adicionales de Control</h2><p>Se agruparán aquí los adicionales que hoy están repartidos entre matriz, centrales, rescates y reglas del cálculo.</p><a class="btn" href="mantenimiento_catalogos_control.php">Catálogos actuales</a><a class="btn sec" href="administrar_matriz.php">Matriz principal</a></section>
<?php else:?><section class="card"><h2>Dependencias</h2><p>Esta pestaña será el mapa de impacto antes de editar o desactivar una regla. La auditoría v208 ya identifica tablas sin referencias literales y fragmentos candidatos a depuración; no se elimina nada automáticamente.</p><a class="btn" href="diagnostico_catalogos.php">Abrir diagnóstico</a></section><?php endif;?>
</main></body></html>
