<?php
session_start();
require_once 'conexion.php';
require_once 'auth.php';
require_once 'control_parametros.php';
asegurarSistemaUsuarios($conexion);
exigirRoles(array('ADMINISTRADOR'));
if (strtoupper((string)($_SERVER['REQUEST_METHOD'] ?? 'GET')) === 'POST') {
    automacValidarCsrf(true);
}
$conexion->set_charset('utf8mb4');
function ce($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function volverCompat($m,$t='ok'){$_SESSION['ctrl_compat_msg']=$m;$_SESSION['ctrl_compat_tipo']=$t;header('Location: mantenimiento_control_compatibilidades.php');exit;}
$instalado=ctrlTablaExiste($conexion,'control_cpu_capacidades')&&ctrlTablaExiste($conexion,'control_tipo_capacidades')&&ctrlTablaExiste($conexion,'control_compatibilidades');
if($instalado && $_SERVER['REQUEST_METHOD']==='POST'){
  $a=$_POST['accion']??'';
  if($a==='cpu'){
    $id=(int)($_POST['cpu_id']??0);$activo=($_POST['activo']??'SI')==='NO'?'NO':'SI';$mrl=($_POST['admite_mrl']??'NO')==='SI'?'SI':'NO';$micro=($_POST['admite_micronivelacion']??'NO')==='SI'?'SI':'NO';$sab=($_POST['admite_maniobra_sabatica']??'NO')==='SI'?'SI':'NO';$ident=trim((string)($_POST['mrl_identidad']??'AUTOMAC'));$obs=trim((string)($_POST['observaciones']??''));
    if(!$id)volverCompat('CPU inválida.','error');
    if(ctrlColumnaExiste($conexion,'control_cpu_capacidades','activo')){
      $st=$conexion->prepare("INSERT INTO control_cpu_capacidades(cpu_id,activo,admite_mrl,admite_micronivelacion,admite_maniobra_sabatica,mrl_identidad,observaciones) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE activo=VALUES(activo),admite_mrl=VALUES(admite_mrl),admite_micronivelacion=VALUES(admite_micronivelacion),admite_maniobra_sabatica=VALUES(admite_maniobra_sabatica),mrl_identidad=VALUES(mrl_identidad),observaciones=VALUES(observaciones)");
      $st->bind_param('issssss',$id,$activo,$mrl,$micro,$sab,$ident,$obs);
    } else {
      $st=$conexion->prepare("INSERT INTO control_cpu_capacidades(cpu_id,admite_mrl,admite_micronivelacion,admite_maniobra_sabatica,mrl_identidad,observaciones) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE admite_mrl=VALUES(admite_mrl),admite_micronivelacion=VALUES(admite_micronivelacion),admite_maniobra_sabatica=VALUES(admite_maniobra_sabatica),mrl_identidad=VALUES(mrl_identidad),observaciones=VALUES(observaciones)");
      $st->bind_param('isssss',$id,$mrl,$micro,$sab,$ident,$obs);
    }
    $st->execute();$st->close();volverCompat('Capacidades de CPU actualizadas.');
  }
  if($a==='tipo'){
    $id=(int)($_POST['ctrltipo_id']??0);$central=($_POST['requiere_central']??'NO')==='SI'?'SI':'NO';$tan=($_POST['permite_tandem']??'NO')==='SI'?'SI':'NO';$rv=($_POST['requiere_velocidad']??'NO')==='SI'?'SI':'NO';$vf=trim((string)($_POST['velocidad_fija_mmin']??''));$vf=$vf===''?null:(float)str_replace(',','.',$vf);$fam=trim((string)($_POST['familia_rescate']??''));$mrl=($_POST['es_mrl']??'NO')==='SI'?'SI':'NO';$act=($_POST['activo']??'NO')==='SI'?'SI':'NO';
    if(!$id)volverCompat('Tipo inválido.','error');
    $st=$conexion->prepare("INSERT INTO control_tipo_capacidades(ctrltipo_id,requiere_central,permite_tandem,requiere_velocidad,velocidad_fija_mmin,familia_rescate,es_mrl,activo) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE requiere_central=VALUES(requiere_central),permite_tandem=VALUES(permite_tandem),requiere_velocidad=VALUES(requiere_velocidad),velocidad_fija_mmin=VALUES(velocidad_fija_mmin),familia_rescate=VALUES(familia_rescate),es_mrl=VALUES(es_mrl),activo=VALUES(activo)");
    $st->bind_param('isssdsss',$id,$central,$tan,$rv,$vf,$fam,$mrl,$act);$st->execute();$st->close();volverCompat('Reglas del tipo actualizadas.');
  }
  if($a==='agregar_compat'){
    $cpu=(int)($_POST['cpu_id']??0);$tipo=(int)($_POST['ctrltipo_id']??0);$sub=(int)($_POST['ctrlsubtipo_id']??0);$obs=trim((string)($_POST['observaciones']??''));
    if(!$cpu||!$tipo||!$sub)volverCompat('Complete CPU, tipo y subtipo.','error');
    $st=$conexion->prepare("INSERT INTO control_compatibilidades(cpu_id,ctrltipo_id,ctrlsubtipo_id,activo,observaciones) VALUES(?,?,?,'SI',?) ON DUPLICATE KEY UPDATE activo='SI',observaciones=VALUES(observaciones)");$st->bind_param('iiis',$cpu,$tipo,$sub,$obs);$st->execute();$st->close();volverCompat('Compatibilidad habilitada.');
  }
  if($a==='toggle_compat'){
    $id=(int)($_POST['compatibilidad_id']??0);$act=($_POST['activo']??'NO')==='SI'?'SI':'NO';if(!$id)volverCompat('Compatibilidad inválida.','error');$st=$conexion->prepare('UPDATE control_compatibilidades SET activo=? WHERE compatibilidad_id=?');$st->bind_param('si',$act,$id);$st->execute();$st->close();volverCompat($act==='SI'?'Compatibilidad activada.':'Compatibilidad desactivada.');
  }
}
$msg=$_SESSION['ctrl_compat_msg']??'';$msgTipo=$_SESSION['ctrl_compat_tipo']??'ok';unset($_SESSION['ctrl_compat_msg'],$_SESSION['ctrl_compat_tipo']);
$cpus=$conexion->query('SELECT cpu_id,cpu_name FROM cpus ORDER BY cpu_id');$tipos=$conexion->query('SELECT ctrltipo_id,ctrltipo_name FROM tipos_control ORDER BY ctrltipo_id');$subs=$conexion->query('SELECT ctrlsubtipo_id,ctrlsubtipo_name FROM subtipos_control ORDER BY ctrlsubtipo_name');
$cpuRows=$tipoRows=$compatRows=null;if($instalado){$cpuRows=$conexion->query("SELECT c.cpu_id,c.cpu_name,cap.* FROM cpus c LEFT JOIN control_cpu_capacidades cap ON cap.cpu_id=c.cpu_id ORDER BY c.cpu_id");$tipoRows=$conexion->query("SELECT t.ctrltipo_id,t.ctrltipo_name,cap.* FROM tipos_control t LEFT JOIN control_tipo_capacidades cap ON cap.ctrltipo_id=t.ctrltipo_id ORDER BY t.ctrltipo_id");$compatRows=$conexion->query("SELECT cc.*,c.cpu_name,t.ctrltipo_name,s.ctrlsubtipo_name FROM control_compatibilidades cc JOIN cpus c ON c.cpu_id=cc.cpu_id JOIN tipos_control t ON t.ctrltipo_id=cc.ctrltipo_id JOIN subtipos_control s ON s.ctrlsubtipo_id=cc.ctrlsubtipo_id ORDER BY c.cpu_name,t.ctrltipo_id,s.ctrlsubtipo_name");}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><title>Compatibilidades de Control · Automac</title><link rel="stylesheet" href="automac-ui.css"><style>
main{max-width:1500px;margin:auto;padding:24px}.card{background:#fff;border:1px solid #dfe5ec;border-radius:12px;padding:16px;margin-bottom:14px}.head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}.btn{display:inline-block;padding:8px 11px;border:0;border-radius:8px;background:#0f5f9c;color:#fff;text-decoration:none;font-weight:700;cursor:pointer}.sec{background:#edf3f7;color:#234}.msg{padding:10px;border-radius:8px;margin:10px 0}.ok{background:#e8f7ef}.error{background:#fdecec}.warn{background:#fff7df;border:1px solid #eed69a;padding:12px;border-radius:9px}.tablewrap{overflow:auto;max-height:560px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:7px;border-bottom:1px solid #e5ebf0;text-align:left;vertical-align:top}th{background:#243746;color:#fff;position:sticky;top:0}input,select{padding:6px;border:1px solid #cbd5df;border-radius:6px}form.inline{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.grid{display:grid;grid-template-columns:repeat(4,minmax(170px,1fr));gap:8px}.mini{font-size:12px;color:#667085}.tag{padding:2px 6px;border-radius:999px;background:#eef3f7}.off{opacity:.55}@media(max-width:900px){.grid{grid-template-columns:1fr 1fr}}</style></head><body><?php require 'menu.php';?><main><section class="card"><div class="head"><div><h1 style="margin:0">Compatibilidades de Control</h1><p class="mini">Fuente mantenible para CPU + tipo + subtipo y capacidades técnicas. No modifica cotizaciones históricas.</p></div><div><a class="btn sec" href="mantenimiento_control.php?tab=catalogos">Volver a Matrices de Control</a></div></div><?php if($msg):?><div class="msg <?=ce($msgTipo)?>"><?=ce($msg)?></div><?php endif;?><?php if(!$instalado):?><div class="warn"><strong>Falta instalar la parametrización v213.</strong> Importe <code>migracion_control_parametrizacion_v213.sql</code>. Mientras tanto el cotizador conserva el comportamiento anterior.</div><?php endif;?></section>
<?php if($instalado):?>
<section class="card"><h2>Capacidades por CPU</h2><div class="tablewrap"><table><thead><tr><th>CPU</th><th>Activo</th><th>MRL</th><th>Micronivelación</th><th>Maniobra sabática</th><th>Identidad MRL</th><th>Observaciones</th><th></th></tr></thead><tbody><?php while($r=$cpuRows->fetch_assoc()):?><tr><form method="post"><?= automacCsrfInput() ?><input type="hidden" name="accion" value="cpu"><input type="hidden" name="cpu_id" value="<?=(int)$r['cpu_id']?>"><td><strong><?=ce($r['cpu_name'])?></strong></td><td><?php if(ctrlColumnaExiste($conexion,'control_cpu_capacidades','activo')):?><select name="activo"><option <?=$r['activo']==='NO'?'selected':''?>>NO</option><option <?=($r['activo']??'SI')==='SI'?'selected':''?>>SI</option></select><?php else:?><span class="tag">SI</span><?php endif;?></td><td><select name="admite_mrl"><option <?=$r['admite_mrl']==='NO'?'selected':''?>>NO</option><option <?=$r['admite_mrl']==='SI'?'selected':''?>>SI</option></select></td><td><select name="admite_micronivelacion"><option <?=$r['admite_micronivelacion']==='NO'?'selected':''?>>NO</option><option <?=$r['admite_micronivelacion']==='SI'?'selected':''?>>SI</option></select></td><td><select name="admite_maniobra_sabatica"><option <?=$r['admite_maniobra_sabatica']==='NO'?'selected':''?>>NO</option><option <?=$r['admite_maniobra_sabatica']==='SI'?'selected':''?>>SI</option></select></td><td><input name="mrl_identidad" value="<?=ce($r['mrl_identidad']??'AUTOMAC')?>" size="12"></td><td><input name="observaciones" value="<?=ce($r['observaciones']??'')?>" size="24"></td><td><button class="btn">Guardar</button></td></form></tr><?php endwhile;?></tbody></table></div></section>
<section class="card"><h2>Comportamiento por tipo de Control</h2><div class="tablewrap"><table><thead><tr><th>Tipo</th><th>Central</th><th>Tándem</th><th>Velocidad seleccionable</th><th>Velocidad fija</th><th>Familia rescate</th><th>Es MRL</th><th>Activo</th><th></th></tr></thead><tbody><?php while($r=$tipoRows->fetch_assoc()):?><tr><form method="post"><?= automacCsrfInput() ?><input type="hidden" name="accion" value="tipo"><input type="hidden" name="ctrltipo_id" value="<?=(int)$r['ctrltipo_id']?>"><td><strong><?=ce($r['ctrltipo_name'])?></strong></td><?php foreach(array('requiere_central','permite_tandem','requiere_velocidad') as $f):?><td><select name="<?=$f?>"><option <?=$r[$f]==='NO'?'selected':''?>>NO</option><option <?=$r[$f]==='SI'?'selected':''?>>SI</option></select></td><?php endforeach;?><td><input name="velocidad_fija_mmin" size="7" value="<?=ce($r['velocidad_fija_mmin'])?>"></td><td><input name="familia_rescate" size="12" value="<?=ce($r['familia_rescate'])?>"></td><td><select name="es_mrl"><option <?=$r['es_mrl']==='NO'?'selected':''?>>NO</option><option <?=$r['es_mrl']==='SI'?'selected':''?>>SI</option></select></td><td><select name="activo"><option <?=$r['activo']==='NO'?'selected':''?>>NO</option><option <?=$r['activo']==='SI'?'selected':''?>>SI</option></select></td><td><button class="btn">Guardar</button></td></form></tr><?php endwhile;?></tbody></table></div></section>
<section class="card"><h2>CPU + Tipo + Subtipo</h2><p class="mini">Esta tabla reemplaza filtros específicos escritos en PHP. Desactivar una combinación impide usarla en nuevas cotizaciones; no borra matrices ni históricos.</p><form method="post" class="grid"><?= automacCsrfInput() ?><input type="hidden" name="accion" value="agregar_compat"><label>CPU<select name="cpu_id" required><option value="">Seleccione</option><?php while($r=$cpus->fetch_assoc()):?><option value="<?=(int)$r['cpu_id']?>"><?=ce($r['cpu_name'])?></option><?php endwhile;?></select></label><label>Tipo<select name="ctrltipo_id" required><option value="">Seleccione</option><?php while($r=$tipos->fetch_assoc()):?><option value="<?=(int)$r['ctrltipo_id']?>"><?=ce($r['ctrltipo_name'])?></option><?php endwhile;?></select></label><label>Subtipo<select name="ctrlsubtipo_id" required><option value="">Seleccione</option><?php while($r=$subs->fetch_assoc()):?><option value="<?=(int)$r['ctrlsubtipo_id']?>"><?=ce($r['ctrlsubtipo_name'])?></option><?php endwhile;?></select></label><label>Observación<input name="observaciones"></label><div><button class="btn">Habilitar combinación</button></div></form><div class="tablewrap" style="margin-top:12px"><table><thead><tr><th>CPU</th><th>Tipo</th><th>Subtipo</th><th>Estado</th><th>Origen/nota</th><th></th></tr></thead><tbody><?php while($r=$compatRows->fetch_assoc()):?><tr class="<?=$r['activo']==='SI'?'':'off'?>"><td><?=ce($r['cpu_name'])?></td><td><?=ce($r['ctrltipo_name'])?></td><td><?=ce($r['ctrlsubtipo_name'])?></td><td><span class="tag"><?=ce($r['activo'])?></span></td><td><?=ce($r['observaciones'])?></td><td><form method="post" class="inline"><?= automacCsrfInput() ?><input type="hidden" name="accion" value="toggle_compat"><input type="hidden" name="compatibilidad_id" value="<?=(int)$r['compatibilidad_id']?>"><input type="hidden" name="activo" value="<?=$r['activo']==='SI'?'NO':'SI'?>"><button class="btn <?=$r['activo']==='SI'?'sec':''?>"><?=$r['activo']==='SI'?'Desactivar':'Activar'?></button></form></td></tr><?php endwhile;?></tbody></table></div></section>
<?php endif;?></main></body></html>
