<?php
require_once 'auth.php';require_once 'conexion.php';exigirRoles(array('ADMINISTRADOR'));
function maE($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$usuarios=0;$r=$conexion->query("SELECT COUNT(*) c FROM usuarios");if($r)$usuarios=(int)$r->fetch_assoc()['c'];
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Administración del Sistema</title><link rel="stylesheet" href="automac-ui.css"><style>.wrap{max-width:1450px;margin:20px auto;padding:0 18px 50px}.hero,.card{background:#fff;border:1px solid #dde5ea;border-radius:14px;padding:18px}.hero{margin-bottom:14px}.hero h1{margin:0 0 6px}.hero p,.card p{color:#64748b}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:13px}.card h2{margin:0 0 7px;font-size:18px}.btn{display:inline-block;padding:9px 12px;border-radius:8px;background:#0f5f9c;color:white;text-decoration:none;font-weight:700}.status{padding:10px 12px;background:#fff7df;border:1px solid #ead8a5;border-radius:10px;margin-top:15px;color:#6d5415}.tag{float:right;background:#edf6f1;color:#17603a;border-radius:999px;padding:4px 8px;font-weight:700;font-size:12px}</style></head><body><?php require 'menu.php';?><main class="wrap"><section class="hero"><h1>Administración del Sistema</h1><p>Funciones administrativas que no pertenecen a una matriz técnica.</p></section><div class="grid">
<section class="card"><span class="tag"><?=$usuarios?> usuarios</span><h2>Usuarios, roles y permisos</h2><p>Altas, modificaciones, estado y restablecimiento de credenciales.</p><a class="btn" href="administrar_usuarios.php">Administrar usuarios</a></section>
<section class="card"><h2>Numeración de documentos</h2><p>Secuencias y numeración de cotizaciones, pedidos y documentos comerciales.</p><a class="btn" href="administrar_numeracion.php">Abrir numeración</a></section>
<section class="card"><h2>Archivo de documentos</h2><p>Consulta y mantenimiento del archivo documental generado por el sistema.</p><a class="btn" href="administrar_documentos.php">Abrir archivo</a></section>
<section class="card"><h2>Condiciones de pago</h2><p>Formas de pago con su código Bejerman. Se seleccionan obligatoriamente al pasar un pedido a Producción.</p><a class="btn" href="mantenimiento_condiciones_pago.php">Administrar condiciones</a></section>
<section class="card"><h2>Integración externa</h2><p>Ruta y formato de nombre de los archivos HTML que toma el sistema externo.</p><a class="btn" href="mantenimiento_integracion_externa.php">Configurar integración</a></section>
<section class="card"><h2>Condiciones comerciales</h2><p>Descuentos predeterminados de Control, Señalización, Accesorios y Repuestos centralizados en base de datos.</p><a class="btn" href="mantenimiento_parametros_comerciales.php">Editar parámetros</a></section>
<section class="card"><h2>Parámetros generales</h2><p>Los parámetros comerciales ya son mantenibles. Las nuevas opciones globales se incorporarán aquí después de validar sus dependencias.</p><a class="btn" href="mantenimiento_parametros_comerciales.php">Abrir parámetros</a></section>
<section class="card"><h2>Auditoría y versión</h2><p>Estado de integridad, código legacy, tablas candidatas a depuración y diferencias entre código y base.</p><a class="btn" href="diagnostico_depuracion.php">Abrir depuración</a></section>
</div><div class="status"><strong>v217:</strong> descuentos predeterminados centralizados. Los documentos históricos conservan los valores con los que fueron emitidos.</div></main></body></html>
