<?php
session_start();
require_once __DIR__ . '/conexion.php';
require_once __DIR__ . '/auth.php';
require_once __DIR__ . '/schema_guard.php';
asegurarSistemaUsuarios($conexion);
exigirRoles(array('ADMINISTRADOR'));
if (strtoupper((string)($_SERVER['REQUEST_METHOD'] ?? 'GET')) === 'POST') automacValidarCsrf(true);
$conexion->set_charset('utf8mb4');

function mrE($valor){return htmlspecialchars((string)$valor,ENT_QUOTES,'UTF-8');}
function mrTablaExiste($conexion,$tabla){return esquemaTablaExiste($conexion,(string)$tabla);}

$mensaje='';$error='';
$tablasRequeridas=array('rescates_opciones','rescates_componentes','tipos_control','subtipos_control');
$faltan=array();
foreach($tablasRequeridas as $tabla)if(!mrTablaExiste($conexion,$tabla))$faltan[]=$tabla;
$tablasPerfilesRescate=mrTablaExiste($conexion,'rescates_compatibilidades')&&mrTablaExiste($conexion,'rescates_codigos_corriente')&&mrTablaExiste($conexion,'rescates_presentacion');

if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        $accion=(string)($_POST['accion']??'');
        if($faltan)throw new Exception('Faltan tablas base de rescates: '.implode(', ',$faltan).'.');
        if(!$tablasPerfilesRescate)throw new Exception('Falta aplicar migracion_perfiles_senalizacion_rescates_2026-10-01.sql.');
        if($accion==='guardar_rescate'){
            $id=(int)($_POST['rescate_id']??0);$clave=strtoupper(trim((string)($_POST['rescate_clave']??'')));$nombre=trim((string)($_POST['rescate_nombre']??''));$familia=strtoupper(trim((string)($_POST['rescate_familia']??'')));$orden=(int)($_POST['rescate_orden']??100);$activo=isset($_POST['rescate_activo'])?'SI':'NO';$modo=strtoupper(trim((string)($_POST['modo_precio']??'COMPONENTES')));$codigoPresentacion=strtoupper(trim((string)($_POST['codigo_presentacion']??'')));
            if($clave===''||$nombre===''||!in_array($familia,array('HIDRAULICO','MRL_IMAN'),true))throw new Exception('Complete clave, nombre y familia válidos.');
            if(!in_array($modo,array('COMPONENTES','ARTICULO_CORRIENTE'),true))throw new Exception('Modo de valorización inválido.');
            if($modo==='COMPONENTES'&&$codigoPresentacion==='')throw new Exception('Indique el código de presentación comercial configurado para el rescate.');
            if($modo==='ARTICULO_CORRIENTE')$codigoPresentacion='';
            $conexion->begin_transaction();
            try{
                $dupe=$conexion->prepare('SELECT rescate_id FROM rescates_opciones WHERE UPPER(TRIM(rescate_clave))=? AND rescate_id<>? LIMIT 1');$dupe->bind_param('si',$clave,$id);$dupe->execute();$hayDuplicado=$dupe->get_result()->num_rows>0;$dupe->close();if($hayDuplicado)throw new Exception('Ya existe un rescate con esa clave interna.');
                if($id>0){$st=$conexion->prepare('UPDATE rescates_opciones SET rescate_clave=?,rescate_nombre=?,rescate_familia=?,rescate_orden=?,rescate_activo=? WHERE rescate_id=?');$st->bind_param('sssisi',$clave,$nombre,$familia,$orden,$activo,$id);}
                else{$st=$conexion->prepare('INSERT INTO rescates_opciones(rescate_clave,rescate_nombre,rescate_familia,rescate_orden,rescate_activo) VALUES(?,?,?,?,?)');$st->bind_param('sssis',$clave,$nombre,$familia,$orden,$activo);}
                if(!$st||!$st->execute())throw new Exception($st?$st->error:$conexion->error);if($id<=0)$id=(int)$st->insert_id;$st->close();
                $st=$conexion->prepare('INSERT INTO rescates_presentacion(rescate_id,modo_precio,codigo_presentacion) VALUES(?,?,?) ON DUPLICATE KEY UPDATE modo_precio=VALUES(modo_precio),codigo_presentacion=VALUES(codigo_presentacion)');$st->bind_param('iss',$id,$modo,$codigoPresentacion);if(!$st->execute())throw new Exception($st->error);$st->close();
                $conexion->commit();$mensaje='Rescate y presentación guardados.';
            }catch(Throwable $e){$conexion->rollback();throw $e;}
        }elseif($accion==='guardar_presentacion'){
            $id=(int)($_POST['rescate_id']??0);$modo=strtoupper(trim((string)($_POST['modo_precio']??'')));$codigo=strtoupper(trim((string)($_POST['codigo_presentacion']??'')));
            if($id<=0||!in_array($modo,array('COMPONENTES','ARTICULO_CORRIENTE'),true))throw new Exception('Seleccione rescate y modo de valorización válidos.');
            if($modo==='COMPONENTES'&&$codigo==='')throw new Exception('La presentación por componentes requiere un código comercial de referencia.');if($modo==='ARTICULO_CORRIENTE')$codigo='';
            $st=$conexion->prepare('INSERT INTO rescates_presentacion(rescate_id,modo_precio,codigo_presentacion) VALUES(?,?,?) ON DUPLICATE KEY UPDATE modo_precio=VALUES(modo_precio),codigo_presentacion=VALUES(codigo_presentacion)');$st->bind_param('iss',$id,$modo,$codigo);if(!$st->execute())throw new Exception($st->error);$st->close();$mensaje='Presentación de rescate actualizada.';
        }elseif($accion==='guardar_compatibilidad'){
            $id=(int)($_POST['compatibilidad_id']??0);$rescate=(int)($_POST['rescate_id']??0);$tipo=(int)($_POST['tipo_control_id']??0);$subtipo=(int)($_POST['subtipo_control_id']??0);$corriente=(int)($_POST['corriente_clave']??0);$activo=isset($_POST['activo'])?'SI':'NO';$orden=(int)($_POST['orden']??100);
            if($rescate<=0||$tipo<=0)throw new Exception('Seleccione rescate y tipo de Control.');
            if($id>0){$st=$conexion->prepare('UPDATE rescates_compatibilidades SET rescate_id=?,tipo_control_id=?,subtipo_control_id=NULLIF(?,0),corriente_clave=NULLIF(?,0),activo=?,orden=? WHERE compatibilidad_id=?');$st->bind_param('iiiisii',$rescate,$tipo,$subtipo,$corriente,$activo,$orden,$id);}
            else{$st=$conexion->prepare('INSERT INTO rescates_compatibilidades(rescate_id,tipo_control_id,subtipo_control_id,corriente_clave,activo,orden) VALUES(?,?,NULLIF(?,0),NULLIF(?,0),?,?)');$st->bind_param('iiiisi',$rescate,$tipo,$subtipo,$corriente,$activo,$orden);}
            if(!$st||!$st->execute())throw new Exception($st?$st->error:$conexion->error);$st->close();$mensaje='Compatibilidad guardada.';
        }elseif($accion==='guardar_codigo_corriente'){
            $id=(int)($_POST['articulo_rescate_id']??0);$rescate=(int)($_POST['rescate_id']??0);$subtipo=(int)($_POST['subtipo_control_id']??0);$corriente=(int)($_POST['corriente_clave']??0);$codigo=strtoupper(trim((string)($_POST['codigo']??'')));$activo=isset($_POST['activo'])?'SI':'NO';$orden=(int)($_POST['orden']??100);
            if($rescate<=0||$subtipo<=0||$corriente<=0||$codigo==='')throw new Exception('Complete variador, corriente y código Bejerman.');
            if($id>0){$st=$conexion->prepare('UPDATE rescates_codigos_corriente SET rescate_id=?,subtipo_control_id=?,corriente_clave=?,codigo=?,activo=?,orden=? WHERE articulo_rescate_id=?');$st->bind_param('iiissii',$rescate,$subtipo,$corriente,$codigo,$activo,$orden,$id);}
            else{$st=$conexion->prepare('INSERT INTO rescates_codigos_corriente(rescate_id,subtipo_control_id,corriente_clave,codigo,activo,orden) VALUES(?,?,?,?,?,?)');$st->bind_param('iiissi',$rescate,$subtipo,$corriente,$codigo,$activo,$orden);}
            if(!$st||!$st->execute())throw new Exception($st?$st->error:$conexion->error);$st->close();$mensaje='Código Bejerman por variador y corriente guardado.';
        }elseif($accion==='guardar_componente'){
            $id=(int)($_POST['componente_id']??0);$rescate=(int)($_POST['rescate_id']??0);$codigo=strtoupper(trim((string)($_POST['componente_codigo']??'')));$regla=strtoupper(trim((string)($_POST['componente_regla']??'')));$cantidad=(float)str_replace(',','.',(string)($_POST['componente_cantidad']??'1'));$orden=(int)($_POST['componente_orden']??100);$activo=isset($_POST['componente_activo'])?'SI':'NO';
            if($rescate<=0||$codigo===''||$cantidad<=0||!in_array($regla,array('FIJO_POR_EQUIPO','PARADAS_MENOS_2'),true))throw new Exception('Complete código, cantidad y fórmula de componente válidos.');
            if($id>0){$st=$conexion->prepare('UPDATE rescates_componentes SET componente_codigo=?,componente_regla=?,componente_cantidad=?,componente_orden=?,componente_activo=? WHERE componente_id=? AND rescate_id=?');$st->bind_param('ssdisii',$codigo,$regla,$cantidad,$orden,$activo,$id,$rescate);}
            else{$st=$conexion->prepare('INSERT INTO rescates_componentes(rescate_id,componente_codigo,componente_regla,componente_cantidad,componente_orden,componente_activo) VALUES(?,?,?,?,?,?)');$st->bind_param('issdis',$rescate,$codigo,$regla,$cantidad,$orden,$activo);}
            if(!$st||!$st->execute())throw new Exception($st?$st->error:$conexion->error);$st->close();$mensaje='Componente de rescate guardado.';
        }else throw new Exception('Acción de mantenimiento no reconocida.');
    }catch(Throwable $e){$error=$e->getMessage();}
}

$tipos=array();$rt=$conexion->query('SELECT ctrltipo_id,ctrltipo_name FROM tipos_control ORDER BY ctrltipo_id');if($rt)while($x=$rt->fetch_assoc())$tipos[]=$x;
$subtipos=array();$rs=$conexion->query('SELECT ctrlsubtipo_id,ctrlsubtipo_name FROM subtipos_control ORDER BY ctrlsubtipo_name');if($rs)while($x=$rs->fetch_assoc())$subtipos[]=$x;
$rescates=array();$compatibilidades=array();$codigosCorriente=array();$componentes=array();
if(!$faltan){
    $r=$conexion->query("SELECT r.*,COALESCE(p.modo_precio,'COMPONENTES') modo_precio,COALESCE(p.codigo_presentacion,'') codigo_presentacion FROM rescates_opciones r LEFT JOIN rescates_presentacion p ON p.rescate_id=r.rescate_id ORDER BY r.rescate_familia,r.rescate_orden,r.rescate_id");if($r)while($x=$r->fetch_assoc())$rescates[]=$x;
    if($tablasPerfilesRescate){
        $r=$conexion->query('SELECT * FROM rescates_compatibilidades ORDER BY rescate_id,orden,compatibilidad_id');if($r)while($x=$r->fetch_assoc())$compatibilidades[]=$x;
        $r=$conexion->query('SELECT * FROM rescates_codigos_corriente ORDER BY rescate_id,orden,subtipo_control_id,corriente_clave');if($r)while($x=$r->fetch_assoc())$codigosCorriente[]=$x;
    }
    $r=$conexion->query('SELECT * FROM rescates_componentes ORDER BY rescate_id,componente_orden,componente_id');if($r)while($x=$r->fetch_assoc())$componentes[]=$x;
}
$preciosMap=array();if(mrTablaExiste($conexion,'lista_precios')){$r=$conexion->query('SELECT precios_codigo,precios_descripcion,precios_costo FROM lista_precios');if($r)while($x=$r->fetch_assoc())$preciosMap[strtoupper(trim((string)$x['precios_codigo']))]=$x;}
function mrBadge($codigo,$precios){$fila=$precios[strtoupper(trim((string)$codigo))]??null;if(!$fila)return '<span class="bad">NO EN LISTA COTIZADOR</span>';return (float)$fila['precios_costo']>0?'<span class="good">PRECIO DISPONIBLE</span>':'<span class="bad">PRECIO 0</span>';}
function mrOptions($filas,$pk,$texto,$seleccionado=0,$todos=false){$html=$todos?'<option value="0">Cualquier valor</option>':'';foreach($filas as $fila){$id=(int)$fila[$pk];$sel=$id===(int)$seleccionado?' selected':'';$html.='<option value="'.$id.'"'.$sel.'>'.mrE($fila[$texto]).'</option>';}return $html;}
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mantenimiento de rescates</title>
<style>
body{font-family:Arial,sans-serif;background:#f3f6f8;color:#19313d;margin:0}.wrap{max-width:1500px;margin:20px auto;padding:0 18px}.card{background:#fff;border:1px solid #dbe4e8;border-radius:8px;padding:16px;margin:14px 0}.toolbar,.row{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.toolbar>*{flex:1}.rescate{border-top:2px solid #dfe7eb;padding-top:14px;margin-top:18px}.rescate summary{font-size:17px;font-weight:700;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:8px;align-items:end;margin:12px 0}.grid label{font-size:12px;font-weight:700}.grid input,.grid select{width:100%;box-sizing:border-box;padding:7px;border:1px solid #c9d6dc;border-radius:5px}.btn{background:#116b51;color:#fff;border:0;border-radius:5px;padding:8px 12px;font-weight:700;cursor:pointer}.btn.secondary{background:#e9eff2;color:#24404e}.status{padding:10px 12px;border-radius:6px;margin:10px 0}.ok{background:#e5f5e9;color:#185b32}.err,.warn{background:#fff0df;color:#805113}.err{background:#fde8e7;color:#932f28}.muted{font-size:12px;color:#607580}.scroll{overflow:auto;margin:8px 0}table{border-collapse:collapse;width:100%;font-size:12px;min-width:900px}th,td{padding:6px;border-bottom:1px solid #e2e9ed;text-align:left;vertical-align:middle}th{background:#edf3f6}td input,td select{min-width:90px;max-width:210px;padding:5px;box-sizing:border-box}code{font-family:Consolas,monospace}.good{color:#176b3a;font-weight:700}.bad{color:#a3342b;font-weight:700}.section{border-top:1px solid #e2e9ed;margin-top:14px;padding-top:10px}.inline{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.inline input,.inline select{padding:6px;border:1px solid #c9d6dc;border-radius:5px}.inline label{font-size:12px}
</style></head><body><?php require 'menu.php';?><main class="wrap"><h1>Mantenimiento de rescates</h1><p class="muted">Edite reglas y códigos usados por el cálculo y la Orden de Fabricación. Los precios no se almacenan aquí: se consultan desde la lista vigente del cotizador.</p><p><a class="btn secondary" href="mantenimiento_control.php?tab=baterias">Volver a Matrices de Control</a></p>
<?php if($mensaje):?><div class="status ok"><?=mrE($mensaje)?></div><?php endif;?><?php if($error):?><div class="status err"><?=mrE($error)?></div><?php endif;?>
<?php if($faltan):?><div class="status err">Faltan tablas base requeridas: <?=mrE(implode(', ',$faltan))?>.</div><?php elseif(!$tablasPerfilesRescate):?><div class="status warn">Aplique la migración <code>migracion_perfiles_senalizacion_rescates_2026-10-01.sql</code> para habilitar compatibilidades y artículos por corriente. No se ejecuta desde esta pantalla.</div><?php endif;?>
<section class="card"><h2>Agregar rescate</h2><form method="post" class="grid"><?=automacCsrfInput()?><input type="hidden" name="accion" value="guardar_rescate"><label>Clave interna<input name="rescate_clave" required></label><label>Nombre / descripción<input name="rescate_nombre" required></label><label>Familia<select name="rescate_familia"><option>HIDRAULICO</option><option>MRL_IMAN</option></select></label><label>Orden<input type="number" name="rescate_orden" value="100"></label><label><input type="checkbox" name="rescate_activo" checked> Activo</label><label>Modo precio<select name="modo_precio"><option>COMPONENTES</option><option>ARTICULO_CORRIENTE</option></select></label><label>Código de presentación<input name="codigo_presentacion" placeholder="Referencia Bejerman"></label><button class="btn">Agregar</button></form></section>
<?php foreach($rescates as $r):$rid=(int)$r['rescate_id'];$compatRes=array_values(array_filter($compatibilidades,function($x)use($rid){return (int)$x['rescate_id']===$rid;}));$codigosRes=array_values(array_filter($codigosCorriente,function($x)use($rid){return (int)$x['rescate_id']===$rid;}));$componentesRes=array_values(array_filter($componentes,function($x)use($rid){return (int)$x['rescate_id']===$rid;}));?>
<details class="card rescate"<?=$r['rescate_activo']==='NO'?'':''?>><summary><?=mrE($r['rescate_clave'])?> · <?=mrE($r['rescate_nombre'])?><?=$r['rescate_activo']==='NO'?' (INACTIVO)':''?></summary>
<form method="post" class="grid"><?=automacCsrfInput()?><input type="hidden" name="accion" value="guardar_rescate"><input type="hidden" name="rescate_id" value="<?=$rid?>"><label>Clave interna<input name="rescate_clave" value="<?=mrE($r['rescate_clave'])?>" required></label><label>Nombre / descripción<input name="rescate_nombre" value="<?=mrE($r['rescate_nombre'])?>" required></label><label>Familia<select name="rescate_familia"><option<?=$r['rescate_familia']==='HIDRAULICO'?' selected':''?>>HIDRAULICO</option><option<?=$r['rescate_familia']==='MRL_IMAN'?' selected':''?>>MRL_IMAN</option></select></label><label>Orden<input type="number" name="rescate_orden" value="<?=(int)$r['rescate_orden']?>"></label><label><input type="checkbox" name="rescate_activo" <?=$r['rescate_activo']==='SI'?'checked':''?>> Activo</label><label>Modo precio<select name="modo_precio"><option<?=$r['modo_precio']==='COMPONENTES'?' selected':''?>>COMPONENTES</option><option<?=$r['modo_precio']==='ARTICULO_CORRIENTE'?' selected':''?>>ARTICULO_CORRIENTE</option></select></label><label>Código presentación<input name="codigo_presentacion" value="<?=mrE($r['codigo_presentacion'])?>" placeholder="Requerido para COMPONENTES"></label><button class="btn">Guardar rescate</button></form>
<div class="section"><h3>Compatibilidad del rescate</h3><form method="post" class="grid"><?=automacCsrfInput()?><input type="hidden" name="accion" value="guardar_compatibilidad"><input type="hidden" name="rescate_id" value="<?=$rid?>"><label>Tipo de Control<select name="tipo_control_id" required><?=mrOptions($tipos,'ctrltipo_id','ctrltipo_name')?></select></label><label>Variador / subtipo<select name="subtipo_control_id"><?=mrOptions($subtipos,'ctrlsubtipo_id','ctrlsubtipo_name',0,true)?></select></label><label>Corriente (A)<input type="number" min="0" step="1" name="corriente_clave" value="0" title="0 indica cualquier corriente"></label><label>Orden<input type="number" name="orden" value="100"></label><label><input type="checkbox" name="activo" checked> Activa</label><button class="btn">Agregar regla</button></form>
<?php if($compatRes):?><div class="scroll"><table><thead><tr><th>Tipo</th><th>Subtipo</th><th>Corriente</th><th>Orden</th><th>Activa</th><th></th></tr></thead><tbody><?php foreach($compatRes as $c):?><tr><form method="post"><?=automacCsrfInput()?><input type="hidden" name="accion" value="guardar_compatibilidad"><input type="hidden" name="compatibilidad_id" value="<?=(int)$c['compatibilidad_id']?>"><input type="hidden" name="rescate_id" value="<?=$rid?>"><td><select name="tipo_control_id"><?=mrOptions($tipos,'ctrltipo_id','ctrltipo_name',(int)$c['tipo_control_id'])?></select></td><td><select name="subtipo_control_id"><?=mrOptions($subtipos,'ctrlsubtipo_id','ctrlsubtipo_name',(int)($c['subtipo_control_id']??0),true)?></select></td><td><input type="number" min="0" step="1" name="corriente_clave" value="<?=(int)($c['corriente_clave']??0)?>"></td><td><input type="number" name="orden" value="<?=(int)$c['orden']?>"></td><td><input type="checkbox" name="activo" <?=$c['activo']==='SI'?'checked':''?>></td><td><button class="btn">Guardar</button></td></form></tr><?php endforeach;?></tbody></table></div><?php else:?><p class="muted">No hay reglas explícitas; el motor conserva el filtro histórico por familia hasta que se agreguen reglas.</p><?php endif;?></div>
<div class="section"><h3>Artículos directos por variador y corriente</h3><form method="post" class="grid"><?=automacCsrfInput()?><input type="hidden" name="accion" value="guardar_codigo_corriente"><input type="hidden" name="rescate_id" value="<?=$rid?>"><label>Variador / subtipo<select name="subtipo_control_id" required><?=mrOptions($subtipos,'ctrlsubtipo_id','ctrlsubtipo_name')?></select></label><label>Corriente (A)<input type="number" min="1" step="1" name="corriente_clave" required></label><label>Código Bejerman<input name="codigo" required></label><label>Orden<input type="number" name="orden" value="100"></label><label><input type="checkbox" name="activo" checked> Activo</label><button class="btn">Agregar artículo</button></form>
<?php if($codigosRes):?><div class="scroll"><table><thead><tr><th>Variador</th><th>Corriente</th><th>Código Bejerman</th><th>Lista cotizador</th><th>Orden</th><th>Activo</th><th></th></tr></thead><tbody><?php foreach($codigosRes as $a):$code=strtoupper(trim((string)$a['codigo']));?><tr><form method="post"><?=automacCsrfInput()?><input type="hidden" name="accion" value="guardar_codigo_corriente"><input type="hidden" name="articulo_rescate_id" value="<?=(int)$a['articulo_rescate_id']?>"><input type="hidden" name="rescate_id" value="<?=$rid?>"><td><select name="subtipo_control_id"><?=mrOptions($subtipos,'ctrlsubtipo_id','ctrlsubtipo_name',(int)$a['subtipo_control_id'])?></select></td><td><input type="number" min="1" name="corriente_clave" value="<?=(int)$a['corriente_clave']?>"></td><td><input name="codigo" value="<?=mrE($code)?>"></td><td><?=mrBadge($code,$preciosMap)?></td><td><input type="number" name="orden" value="<?=(int)$a['orden']?>"></td><td><input type="checkbox" name="activo" <?=$a['activo']==='SI'?'checked':''?>></td><td><button class="btn">Guardar</button></td></form></tr><?php endforeach;?></tbody></table></div><?php endif;?></div>
<div class="section"><h3>Componentes y cantidades</h3><form method="post" class="grid"><?=automacCsrfInput()?><input type="hidden" name="accion" value="guardar_componente"><input type="hidden" name="rescate_id" value="<?=$rid?>"><label>Código Bejerman<input name="componente_codigo" required></label><label>Fórmula<select name="componente_regla"><option>FIJO_POR_EQUIPO</option><option>PARADAS_MENOS_2</option></select></label><label>Cantidad base<input type="number" min="0.0001" step="0.0001" name="componente_cantidad" value="1" required></label><label>Orden<input type="number" name="componente_orden" value="100"></label><label><input type="checkbox" name="componente_activo" checked> Activo</label><button class="btn">Agregar componente</button></form>
<?php if($componentesRes):?><div class="scroll"><table><thead><tr><th>Código</th><th>Lista cotizador</th><th>Fórmula</th><th>Cantidad base</th><th>Orden</th><th>Activo</th><th></th></tr></thead><tbody><?php foreach($componentesRes as $c):$code=strtoupper(trim((string)$c['componente_codigo']));?><tr><form method="post"><?=automacCsrfInput()?><input type="hidden" name="accion" value="guardar_componente"><input type="hidden" name="componente_id" value="<?=(int)$c['componente_id']?>"><input type="hidden" name="rescate_id" value="<?=$rid?>"><td><input name="componente_codigo" value="<?=mrE($code)?>"></td><td><?=mrBadge($code,$preciosMap)?></td><td><select name="componente_regla"><option<?=$c['componente_regla']==='FIJO_POR_EQUIPO'?' selected':''?>>FIJO_POR_EQUIPO</option><option<?=$c['componente_regla']==='PARADAS_MENOS_2'?' selected':''?>>PARADAS_MENOS_2</option></select></td><td><input type="number" min="0.0001" step="0.0001" name="componente_cantidad" value="<?=mrE($c['componente_cantidad'])?>"></td><td><input type="number" name="componente_orden" value="<?=(int)$c['componente_orden']?>"></td><td><input type="checkbox" name="componente_activo" <?=$c['componente_activo']==='SI'?'checked':''?>></td><td><button class="btn">Guardar</button></td></form></tr><?php endforeach;?></tbody></table></div><?php endif;?></div>
</details><?php endforeach;?>
</main></body></html>