<?php
/* v38 - Pedido en una linea + Botonera comercial agrupada (base + paradas + indicador). */
session_start(); include 'conexion.php';
 require_once 'auth.php'; asegurarSistemaUsuarios($conexion);
exigirRoles(array('ADMINISTRADOR','COMERCIAL')); require_once 'sistema_comercial.php'; asegurarSistemaComercial($conexion);
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT); if(!$id)die('Pedido inválido.');
$st=$conexion->prepare("SELECT p.*,c.cotizacion_numero,COALESCE(p.referencia,c.referencia) AS referencia,cl.clientes_codigo,cl.clientes_nomfantasia,cl.clientes_emails,cl.clientes_telefono,l.lista_nombre,l.lista_fecha_archivo,l.lista_estado,COALESCE(u.usuario_nombre,p.usuario,'') AS ejecutado_por FROM pedidos p LEFT JOIN cotizaciones c ON c.cotizacion_id=p.cotizacion_id JOIN clientes cl ON cl.clientes_id=p.cliente_id JOIN listas_precios_importaciones l ON l.lista_id=p.lista_id LEFT JOIN usuarios u ON u.usuario_id=p.usuario_id WHERE p.pedido_id=?");
$st->bind_param('i',$id);$st->execute();$p=$st->get_result()->fetch_assoc();$st->close();if(!$p)die('Pedido inexistente');
$fechaVersionPedido=fechaVersionActualPedido($p);
$st=$conexion->prepare('SELECT * FROM pedidos_detalle WHERE pedido_id=? ORDER BY orden_visual');$st->bind_param('i',$id);$st->execute();$rrDetalle=$st->get_result();$detallesVista=array();while($filaDetalle=$rrDetalle->fetch_assoc())$detallesVista[]=$filaDetalle;$datosAgrupacion=json_decode((string)($p['datos_formulario']??''),true);if(!is_array($datosAgrupacion))$datosAgrupacion=array();$solicitanteCliente=trim((string)($datosAgrupacion['solicitante_cliente']??''));$detallesVista=agruparBotoneraCabinaPresentacion($detallesVista,$datosAgrupacion);
require_once __DIR__ . '/envio_documentos.php';
$envioDoc=envioDocPreparar($conexion,array('tipo'=>'pedido','numero'=>numeroDocumentoVisible((string)$p['pedido_numero']),'revision'=>(int)($p['revision']??0),'cliente_id'=>(int)($p['cliente_id']??0),'cliente'=>trim((string)($p['clientes_nomfantasia']??$p['clientes_codigo']??'')),'email'=>trim((string)($p['clientes_emails']??'')),'telefono'=>trim((string)($p['clientes_telefono']??'')),'referencia'=>trim((string)($p['referencia']??'')),'usuario'=>trim((string)($_SESSION['usuario_nombre']??'')),'pdf_url'=>'descargar_pdf_pedido.php?id='.(int)$id));
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars(numeroDocumentoVisible($p['pedido_numero']))?></title><style>
body{font-family:Arial;background:#f4f4f9;margin:18px;color:#202124}.caja{background:white;padding:18px;border-radius:8px;max-width:1300px;margin:auto}nav{margin-bottom:14px}nav a,.btn{display:inline-block;padding:8px 12px;margin:2px;background:#343a40;color:white;text-decoration:none;border-radius:5px;border:0;font-weight:bold}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}th{background:#212529;color:white}.verde{background:#198754}.azul{background:#0d6efd}.total{font-size:20px;color:#198754}.acciones{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}
</style></head><body><div class="caja"><?php require __DIR__ . '/menu.php'; ?>
<h1><?=htmlspecialchars(numeroDocumentoVisible($p['pedido_numero']))?> <span style="font-size:18px;background:#ffc107;padding:5px 9px;border-radius:5px;">REVISIÓN <?= (int)($p['revision']??0) ?></span><?php if(($p['estado']??'')==='ANULADO'): ?> <span style="font-size:18px;background:#dc3545;color:#fff;padding:5px 9px;border-radius:5px;">ANULADO</span><?php endif; ?></h1>
<?php envioDocRender($envioDoc); ?>
<p><b>Cotización origen:</b> <?=htmlspecialchars($p['cotizacion_numero'] ? numeroDocumentoVisible($p['cotizacion_numero']) : 'PEDIDO DIRECTO')?></p>
<p><b>Cliente:</b> <?=htmlspecialchars($p['clientes_codigo'].' — '.$p['clientes_nomfantasia'])?></p><p><b>Solicitante:</b> <?=htmlspecialchars($solicitanteCliente!==''?$solicitanteCliente:'—')?></p>
<p><b>Referencia:</b> <?=htmlspecialchars($p['referencia']?:'—')?></p>
<p><b>Responsable comercial:</b> <?=htmlspecialchars($p['ejecutado_por']?:'—')?></p>
<p><b>Base de precios:</b> <?=htmlspecialchars(descripcionBaseBejerman($p))?></p><?php if(($p['estado']??'')==='ANULADO'): ?><p style="padding:10px;background:#f8d7da;border:1px solid #f1aeb5;border-radius:6px;color:#842029"><b>Anulación:</b> <?=htmlspecialchars($p['anulacion_motivo']?:'Sin motivo registrado')?><?php if(!empty($p['anulacion_fecha'])): ?> · <?=htmlspecialchars(fechaHoraAr($p['anulacion_fecha']))?><?php endif; ?></p><?php endif; ?>
<?php if(!empty($p['fecha_paso_produccion'])):?><p><b>Producción:</b> <?=htmlspecialchars($p['estado'])?> · Entrega <?=htmlspecialchars($p['fecha_entrega']?:'—')?> · Pago (<?=htmlspecialchars($p['condicion_pago_codigo']?:'—')?>) <?=htmlspecialchars($p['condicion_pago_descripcion']?:'—')?> · Estados <?=htmlspecialchars(($p['estado_control_produccion']?:'-').' / '.($p['estado_senalizacion_produccion']?:'-').' / '.($p['estado_iep_produccion']?:'-'))?></p><?php endif;?>
<table><tr><th>Concepto</th><th>Código</th><th>Descripción</th><th>Cantidad</th><th>Unitario</th><th>Total</th></tr><?php foreach($detallesVista as $x):?><tr><td><?=htmlspecialchars($x['concepto'])?></td><td><?=htmlspecialchars($x['codigo'])?></td><td><?=htmlspecialchars($x['descripcion'])?></td><td><?=number_format($x['cantidad'],2,',','.')?></td><td>$<?=number_format(ceil((float)$x['precio_unitario']),0,',','.')?></td><td>$<?=number_format(ceil((float)$x['importe_total']),0,',','.')?></td></tr><?php endforeach;?></table>
<p class="total"><b>Total: $<?=number_format(ceil((float)$p['total']),0,',','.')?></b></p>
<div class="acciones"><a class="btn" href="pedidos.php">VOLVER A PEDIDOS</a><?php if(($p['estado']??'')!=='ANULADO'): ?><a class="btn verde" href="pasar_produccion.php?id=<?=$id?>"><?=!empty($p['fecha_paso_produccion'])?'REVISAR / REGENERAR PRODUCCIÓN':'PASAR A PRODUCCIÓN'?></a><a class="btn" style="background:#dc3545" href="index.php?editar_pedido=<?=$id?>">MODIFICAR PEDIDO</a><a class="btn" style="background:#9b1c2c" href="anular_documento.php?tipo=pedido&id=<?=$id?>">ANULAR <?=($p['pedido_tipo']??'OBRA')==='OBRA'?'OBRA':'PEDIDO'?></a><?php endif; ?><a class="btn azul" href="generar_pdf_pedido.php?id=<?=$id?>" target="_blank">VER / DESCARGAR PDF</a><?php if(($p['estado']??'')!=='ANULADO' && (int)($p['revision'] ?? 0)>0):?><a class="btn verde" href="generar_paquete_modificacion_pedido.php?id=<?=$id?>&destino=produccion" target="_blank">PAQUETE PRODUCCIÓN</a><a class="btn verde" href="generar_paquete_modificacion_pedido.php?id=<?=$id?>&destino=administracion" target="_blank">PAQUETE ADMINISTRACIÓN</a><?php endif;?></div>
<h2>Historial de revisiones</h2>
<table><tr><th>Revisión</th><th>Fecha</th><th>Motivo</th><th>Usuario</th><th>Detalle</th><th>PDF</th></tr>
<tr><td><strong><?=htmlspecialchars(etiquetaVersionPedido((int)($p['revision']??0)))?> (actual)</strong></td><td><?=htmlspecialchars(fechaHoraAr($fechaVersionPedido))?></td><td><?=nl2br(htmlspecialchars(motivoVersionPedido($conexion,(int)$id,(int)($p['revision']??0))))?></td><td><?=htmlspecialchars($p['ejecutado_por']?:'—')?></td><td><span class="btn verde">Vista actual</span></td><td><a class="btn azul" href="generar_pdf_pedido.php?id=<?=$id?>" target="_blank">VER PDF</a></td></tr>
<?php $hr=$conexion->prepare('SELECT revision,fecha_revision,motivo_modificacion,usuario FROM pedidos_revisiones WHERE pedido_id=? ORDER BY revision DESC');$hr->bind_param('i',$id);$hr->execute();$hist=$hr->get_result(); while($h=$hist->fetch_assoc()): $revHist=(int)$h['revision']; $fechaHist=fechaVersionHistoricaPedido($conexion,(int)$id,$revHist,(string)($p['fecha_creacion']??'')); $motivoHist=motivoVersionPedido($conexion,(int)$id,$revHist);?><tr><td><?=htmlspecialchars(etiquetaVersionPedido($revHist))?></td><td><?=htmlspecialchars(fechaHoraAr($fechaHist))?></td><td><?=nl2br(htmlspecialchars($motivoHist))?></td><td><?=htmlspecialchars($h['usuario']?:'—')?></td><td><a class="btn azul" href="ver_revision_pedido.php?pedido_id=<?=$id?>&revision=<?=$revHist?>">VER VERSIÓN</a></td><td><a class="btn verde" href="generar_pdf_revision.php?tipo=pedido&id=<?=$id?>&revision=<?=$revHist?>" target="_blank">VER PDF</a></td></tr><?php endwhile;$hr->close();?></table>
</div></body></html>